source 'https://github.com/CocoaPods/Specs.git'

target 'ABSegmentedViewController', :exclusive => true do
  pod "ABSegmentedViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ABSegmentedViewController", :path => "../"

  
end
